tap 'homebrew/bundle'
tap 'homebrew/core'
brew 'bazaar'
brew 'curl'
brew 'git'
brew 'gnupg'
brew 'go'
brew 'hub'
brew 'mas'
brew 'mercurial'
brew 'neovim'
brew 'netcat'
brew 'node'
brew 'pinentry-mac'
brew 'php'
brew 'rbenv'
brew 'ssh-copy-id'
brew 'tree'
brew 'wget'
brew 'yarn'
brew 'zsh'

tap 'caskroom/cask'
tap 'caskroom/versions'
cask 'disk-inventory-x'
cask 'dropbox'
cask 'firefox'
cask 'google-cloud-sdk'
cask 'iterm2'
cask 'keka'
cask 'slack'
cask 'spectacle'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'

mas "Amphetamine", id: 937984704
mas "Wunderlist", id: 410628904
mas "Xcode", id: 497799835
