code --install-extension artdiniz.quitcontrol-vscode
code --install-extension astro-build.astro-vscode
code --install-extension eseom.nunjucks-template
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension usernamehw.errorlens
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension ms-azuretools.vscode-docker
code --install-extension rust-lang.rust-analyzer
code --install-extension syler.sass-indented
code --install-extension tamasfe.even-better-toml
code --install-extension waderyan.gitblame
